name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: '6.0.x'

      - name: Compile
        run: dotnet build Colorful.sln

  build:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Discord
        uses: docker/build-push-action@v2.7.0
        with:
          file: Colorful.Discord/Dockerfile
          context: .
          push: false
          
      - name: Build Web
        uses: docker/build-push-action@v2.7.0
        with:
          file: Colorful.Web/Dockerfile
          context: .
          push: false
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Deploy Discord
        uses: docker/build-push-action@v2.7.0
        with:
          file: Colorful.Discord/Dockerfile
          context: .
          push: true
          tags: sirmeepington/colorfuldiscord:latest
          
      - name: Deploy Web
        uses: docker/build-push-action@v2.7.0
        with:
          file: Colorful.Web/Dockerfile
          context: .
          push: true
          tags: sirmeepington/colorfulweb:latest
